import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@/styles/globals.css";
import CursorGlow from "@/components/CursorGlow/CursorGlow";
import { ThemeProvider } from "next-themes";
import AppNavbar from "@/components/Navigation/AppNavbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
      <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
        >
          <AppNavbar />
          {children}
          <CursorGlow />
        </ThemeProvider>
      </body>
    </html>
  );
}
